### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by hellmo718** [VincentHancoder/SSGD#1]
请问这个数据集在哪里呢？

**Comment by VincentHancoder** [comment]
您好，最近文章刚刚结束camera ready，等到正式publish之后数据集会进行开源

**Comment by hellmo718** [comment]
好的，谢谢呢

**Comment by VincentHancoder** [comment]
不客气～后续开源后欢迎引用哈，文章已经挂在arxiv上了

**Comment by Yangr116** [comment]
https://cloud.tsinghua.edu.cn/f/0a03abd18c0f4038a9c4/?dl=1
