### ISSUE TITLE
The Description of Datasets

### ISSUE THREAD

**Issue by Chan-Sun** [VincentHancoder/SSGD#2]
Hi! I have read your ICASSP 2023 paper and download the dataset from the link in the README.

But the dataset I download doesn't correspond with the description in your paper.

There are three folders in the zipfile, including lb101 with 1538 images, lb201 with 1440 images and lb401 with 694 images.

Is there any update on the description of data?

**Comment by VincentHancoder** [comment]
Hello~thanks to your reminding, we found our last version of dataset are one of the old versions during collecting data. Now we

have already commited the correct version of SSGD downloading links to our repo. They are accessible to you now.

**Comment by Chan-Sun** [comment]
It is clear now. Thanks for your contribution.

**Comment by Chan-Sun** [comment]
Sorry to bother, but there is another issue. The annotation information I collected from lb101.json and lb201.json do not correspond with the information in the paper. Here is the annotation table I collected.

| crack |  broken |  spot |  scratch |  light-leakage |  blot |  broken-membrane |
|:-----:|:-------:|:-----:|:--------:|:--------------:|:-----:|:----------------:|
|  1000 |   177   |  105  |    307   |       66       |   10  |        20        |
|  789  |   163   |  842  |    480   |       11       |   13  |        60        |

And here is the description in the paper `Section 2.2. Dataset Properties`

>Part I Content: the possession situation of each type of defects is that crack: 988, broken: 304, spot: 175, scratch: 99, >light-leakage: 63, blot: 18, broken-membrane: 10. 
>Part II Content: the possession situation of each type of defects is that crack: 787, broken: 756, spot: 467, scratch: >163, light-leakage: 60, blot: 13, broken-membrane: 11.

**Comment by VincentHancoder** [comment]
Thanks a lot for your checking. There may be something going wrong when data cleaning. I'll check it soon.

**Comment by VincentHancoder** [comment]
We have updated the latest annotations file to repo. You can have a look and check it now.

**Comment by Chan-Sun** [comment]
looks good to me now. Thanks for your quick response.
